# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\WebApp.zip'
    artifact: 'WebAppArtifact'
    publishLocation: 'pipeline'

#Your build pipeline references an undefined variable named ‘VERACODE_API_ID’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘VERACODE_API_SECRET’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

- bash: |
   curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
   unzip pipeline-scan-LATEST.zip pipeline-scan.jar
   java -jar pipeline-scan.jar  --veracode_api_id "$(VERACODE_API_ID)" --veracode_api_key "$(VERACODE_API_SECRET)" --file "$(Build.ArtifactStagingDirectory)/WebApp.zip" --project_name "$(Build.DefinitionName)"  --project_url "${CI_REPOSITORY_URL}"  --project_ref "$(Build.Repository.Name)" --fail_on_severity="Very High,High"
   
  displayName: 'Run pipeline scan'
  continueOnError: true

- task: VeracodePipelineResultImport@0
  inputs:
    pipelineResultsJson: 'results.json'
    outputResultsSarif: 'veracode-results.sarif'
    findingRuleLevel: '4:3:0'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'veracode-results.sarif'
    artifact: 'CodeAnalysisLogs'
    publishLocation: 'pipeline'